[package]
name = "zpx_adapter_cctp_v2"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["lib"]

[dependencies]
anchor-lang = { version = "0.27.0", features = ["init-if-needed"] }
solana-program = "1.14.16"

[features]
default = []
